# This is a basic workflow to help you get started with Actions
# As suggested here: https://stackoverflow.com/questions/57549439/how-do-i-use-docker-with-github-actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: change workdir
        run: cd $HOME/work/campingliste/campingliste
      - name: Run converter
        run: ./convert.sh
    # https://github.com/marketplace/actions/github-release-create-update-and-upload-assets#advanced-example
      - name: Set enviroment for github-release
        run: |
          echo ::set-env name=RELEASE_TAG::"v1.0.0"
          echo ::set-env name=RELEASE_NAME::"$GITHUB_WORKFLOW"
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          files: >
            lebensmittel.pdf
            misc.pdf
            kuechenkiste.pdf